dist: bionic
sudo: required
language: rust
services:
- docker
cache:
  cargo: true
  directories:
  - "~/.npm"
notifications:
  email: false

install:
  - rustup install nightly
  - cargo --version
  - docker --version
  - wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
  - sudo apt-add-repository "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-10 main"
  - sudo apt-get update
  - sudo apt-get install -y clang-7 --allow-unauthenticated
  - sudo apt-get install -y openssl --allow-unauthenticated
  - sudo apt-get install -y libssl-dev --allow-unauthenticated
  - sudo apt-get install -y libssl1.1 --allow-unauthenticated
  - clang-7 --version
  - nvm install node
  - node --version
  - npm install

script:
  - npm run lint
  - npm run flow
  - npm run build:program-rust
  - npm run test:program-rust
  - npm run cluster:localnet
  - npm run localnet:update
  - npm run localnet:up
  - npm run start
  - npm run build:program-c
  - npm run start
  - npm run localnet:down
